spring:
  application:
    name: rss25SB
  datasource:
    url: jdbc:postgresql://bcdinkaltttrftd7aykw-postgresql.services.clever-cloud.com:50013/bcdinkaltttrftd7aykw
    username: ufukbgb6bn4jxvoueqwd
    password: bwKeXGt7AgL22r8GyhtrJVWqcf1RWS
    driver-class-name: org.postgresql.Driver
    #hikari:
    #  maximum-pool-size: 1
    #  idle-timeout: 10000 # 10 secondes avant de fermer une connexion inactive
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
